export const apiHomes = [ // eslint-disable-line import/prefer-default-export
  {
    "title": "2424 Boylston st Boston - Fenway",
    "id": "11564783",
    "slug": "2424-boylston-st-boston-fenway",
    "cardinalDirection": null,
    "city": "Boston",
    "neighborhood": "Fenway",
    "offer": "rent",
    "units": [
      {
        "amiQualification": 80,
        "bedrooms": 4,
        "price": 2400,
        "priceRate": "monthly",
        "id": "11564791",
      },
    ],
    "incomeRestricted": true,
    "assignment": "waitlist",
    "listingDate": "2020-04-08T04:09:38Z",
    "applicationDueDate": "",
    "type": "",
  },
  {
    "title": "45 Lothrop Street Beverly -",
    "id": "11564785",
    "slug": "45-lothrop-street-beverly",
    "cardinalDirection": "north",
    "city": "Beverly",
    "neighborhood": "",
    "offer": "rent",
    "units": [
      {
        "amiQualification": 50,
        "bedrooms": 0,
        "price": 800,
        "priceRate": "monthly",
        "id": "11564793",
      },
      {
        "amiQualification": 50,
        "bedrooms": 0,
        "price": 800,
        "priceRate": "monthly",
        "id": "11564794",
      },
    ],
    "incomeRestricted": true,
    "assignment": "lottery",
    "listingDate": "2020-04-08T04:09:38Z",
    "applicationDueDate": "2020-04-30",
    "type": "sro",
  },
  {
    "title": "12 Malcolm X Blvd Boston - Roxbury",
    "id": "11564786",
    "slug": "12-malcolm-x-blvd-boston-roxbury",
    "cardinalDirection": null,
    "city": "Boston",
    "neighborhood": "Roxbury",
    "offer": "rent",
    "units": [
      {
        "amiQualification": 100,
        "bedrooms": 3,
        "price": 400000,
        "priceRate": "once",
        "id": "11564787",
      },
      {
        "amiQualification": 80,
        "bedrooms": 2,
        "price": 300000,
        "priceRate": "once",
        "id": "11564788",
      },
      {
        "amiQualification": 80,
        "bedrooms": 2,
        "price": 1500,
        "priceRate": "monthly",
        "id": "11564789",
      },
      {
        "amiQualification": 60,
        "bedrooms": 1,
        "price": 1200,
        "priceRate": "monthly",
        "id": "11564792",
      },
    ],
    "incomeRestricted": true,
    "assignment": "first",
    "listingDate": "2020-04-08T04:09:38Z",
    "applicationDueDate": "",
    "type": "apt",
  },
  {
    "title": "1200  Massachusetts Avenue Cambridge -",
    "id": "11564784",
    "slug": "1200-massachusetts-avenue-cambridge",
    "cardinalDirection": "west",
    "city": "Cambridge",
    "neighborhood": "",
    "offer": "sale",
    "units": [
      {
        "amiQualification": 120,
        "bedrooms": 3,
        "price": 450000,
        "priceRate": "once",
        "id": "11564790",
      },
    ],
    "incomeRestricted": false,
    "assignment": "first",
    "listingDate": "2020-04-08T04:09:38Z",
    "applicationDueDate": "",
    "type": "",
  },
  // {
  //   "title": "12 Malcolm X Blvd Boston - Roxbury",
  //   "id": "11564786",
  //   "slug": "12-malcolm-x-blvd-boston-roxbury",
  //   "cardinalDirection": null,
  //   "city": "Boston",
  //   "neighborhood": "Roxbury",
  //   "offer": "sale",
  //   "units": [
  //     {
  //       "amiQualification": 100,
  //       "bedrooms": 3,
  //       "price": 400000,
  //       "priceRate": "once",
  //       "id": "11564787",
  //     },
  //     {
  //       "amiQualification": 80,
  //       "bedrooms": 2,
  //       "price": 300000,
  //       "priceRate": "once",
  //       "id": "11564788",
  //     },
  //     {
  //       "amiQualification": 80,
  //       "bedrooms": 2,
  //       "price": 1500,
  //       "priceRate": "monthly",
  //       "id": "11564789",
  //     },
  //     {
  //       "amiQualification": 60,
  //       "bedrooms": 1,
  //       "price": 1200,
  //       "priceRate": "monthly",
  //       "id": "11564792",
  //     },
  //   ],
  //   "incomeRestricted": true,
  //   "assignment": "first",
  //   "listingDate": "2020-04-08T04:09:38Z",
  //   "applicationDueDate": "",
  //   "type": "condo",
  // },
];
