export default [
  {
    "title": "The Viridian",
    "id": "11564932",
    "slug": "viridian",
    "cardinalDirection": null,
    "city": "Boston",
    "neighborhood": "Fenway",
    "offer": "rent",
    "units": [
      {
        "id": "11564932-1",
        "count": 1,
        "amiQualification": 120,
        "bedrooms": 3,
        "price": 2947,
        "priceRate": "monthly",
      },
    ],
    "assignment": "first",
    "listingDate": "2020-05-13T17:41:17Z",
    "applicationDueDate": "",
    "type": "apt",
  },
  {
    "title": "The Point at Marlborough",
    "id": "11564929",
    "slug": "point-marlborough",
    "cardinalDirection": "west",
    "city": "Marlborough",
    "neighborhood": null,
    "offer": "rent",
    "units": [
      {
        "id": "11564929-1",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 1,
        "price": 1360,
        "priceRate": "monthly",
      },
      {
        "id": "11564929-2",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 2,
        "price": 1589,
        "priceRate": "monthly",
      },
    ],
    "assignment": "waitlist",
    "listingDate": "2020-05-13T17:41:17Z",
    "applicationDueDate": "",
    "type": "apt",
  },
  {
    "title": "6 Lorne Street",
    "id": "11564931",
    "slug": "6-lorne-street",
    "cardinalDirection": null,
    "city": "Boston",
    "neighborhood": "Dorchester",
    "offer": "rent",
    "units": [
      {
        "id": "11564931-1",
        "count": 1,
        "amiQualification": 100,
        "bedrooms": 4,
        "price": 2500,
        "priceRate": "monthly",
      },
    ],
    "assignment": "first",
    "listingDate": "2020-05-13T17:41:17Z",
    "applicationDueDate": "",
    "type": "1-3-family",
  },
  {
    "title": "660 Washington Apartments",
    "id": "11564928",
    "slug": "660-washington-apartments",
    "cardinalDirection": null,
    "city": "Boston",
    "neighborhood": "Chinatown",
    "offer": "rent",
    "units": [
      {
        "id": "11564928-1",
        "count": 1,
        "amiQualification": 120,
        "bedrooms": 1,
        "price": 1876,
        "priceRate": "monthly",
      },
    ],
    "assignment": "first",
    "listingDate": "2020-05-13T17:41:17Z",
    "applicationDueDate": "",
    "type": "apt",
  },
  {
    "title": "Lodge at Foxborough",
    "id": "11564930",
    "slug": "lodge-foxborough",
    "cardinalDirection": "south",
    "city": "Foxborough",
    "neighborhood": null,
    "offer": "rent",
    "units": [
      {
        "id": "11564930-1",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 1,
        "price": 1424,
        "priceRate": "monthly",
      },
      {
        "id": "11564930-2",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 2,
        "price": 1694,
        "priceRate": "monthly",
      },
    ],
    "assignment": "waitlist",
    "listingDate": "2020-05-13T17:41:17Z",
    "applicationDueDate": "",
    "type": "apt",
  },
  {
    "title": "Emery Flats",
    "id": "11564925",
    "slug": "emery-flats",
    "cardinalDirection": "north",
    "city": "Woburn",
    "neighborhood": null,
    "offer": "rent",
    "units": [
      {
        "id": "11564925-1",
        "count": 2,
        "amiQualification": 80,
        "bedrooms": 0,
        "price": 1446,
        "priceRate": "monthly",
      },
      {
        "id": "11564925-2",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 1,
        "price": 1535,
        "priceRate": "monthly",
      },
      {
        "id": "11564925-3",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 1,
        "price": 1535,
        "priceRate": "monthly",
      },
    ],
    "assignment": "waitlist",
    "listingDate": "2020-05-13T15:54:34Z",
    "applicationDueDate": "",
    "type": "apt",
  },
  {
    "title": "The Beverly",
    "id": "11564927",
    "slug": "beverly",
    "cardinalDirection": null,
    "city": "Boston",
    "neighborhood": "North End",
    "offer": "rent",
    "units": [
      {
        "id": "11564927-1",
        "count": 1,
        "amiQualification": 150,
        "bedrooms": 1,
        "price": 2945,
        "priceRate": "monthly",
      },
      {
        "id": "11564927-2",
        "count": 1,
        "amiQualification": 140,
        "bedrooms": 0,
        "price": 2412,
        "priceRate": "monthly",
      },
      {
        "id": "11564927-3",
        "count": 1,
        "amiQualification": 140,
        "bedrooms": 1,
        "price": 2646,
        "priceRate": "monthly",
      },
      {
        "id": "11564927-4",
        "count": 1,
        "amiQualification": 140,
        "bedrooms": 2,
        "price": 3470,
        "priceRate": "monthly",
      },
      {
        "id": "11564927-5",
        "count": 1,
        "amiQualification": 140,
        "bedrooms": 3,
        "price": 4000,
        "priceRate": "monthly",
      },
      {
        "id": "11564927-6",
        "count": 1,
        "amiQualification": 150,
        "bedrooms": 0,
        "price": 2650,
        "priceRate": "monthly",
      },
      {
        "id": "11564927-7",
        "count": 1,
        "amiQualification": 165,
        "bedrooms": 0,
        "price": 2850,
        "priceRate": "monthly",
      },
      {
        "id": "11564927-8",
        "count": 1,
        "amiQualification": 165,
        "bedrooms": 1,
        "price": 3195,
        "priceRate": "monthly",
      },
    ],
    "assignment": "first",
    "listingDate": "2020-05-13T15:54:34Z",
    "applicationDueDate": "",
    "type": "apt",
  },
  {
    "title": "71 Topliff Street",
    "id": "11564926",
    "slug": "71-topliff-street",
    "cardinalDirection": null,
    "city": "Boston",
    "neighborhood": "Dorchester",
    "offer": "rent",
    "units": [
      {
        "id": "11564926-1",
        "count": 3,
        "amiQualification": 120,
        "bedrooms": 3,
        "price": 3200,
        "priceRate": "monthly",
      },
    ],
    "assignment": "first",
    "listingDate": "2020-05-13T15:54:34Z",
    "applicationDueDate": "",
    "type": "1-3-family",
  },
  {
    "title": "Medfield Meadows",
    "id": "11564796",
    "slug": "medfield-meadows",
    "cardinalDirection": "west",
    "city": "Medfield",
    "neighborhood": null,
    "offer": "rent",
    "units": [
      {
        "id": "11564796-1",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 1,
        "price": 1660,
        "priceRate": "monthly",
      },
      {
        "id": "11564796-2",
        "count": 4,
        "amiQualification": 80,
        "bedrooms": 2,
        "price": 1825,
        "priceRate": "monthly",
      },
      {
        "id": "11564796-3",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 3,
        "price": 2002,
        "priceRate": "monthly",
      },
    ],
    "assignment": "lottery",
    "listingDate": "2020-05-08T17:18:44Z",
    "applicationDueDate": "2020-06-15",
    "type": "apt",
  },
  {
    "title": "The Coolidge at Sudbury Phase 2",
    "id": "11564798",
    "slug": "coolidge-sudbury-phase-2",
    "cardinalDirection": "west",
    "city": "Sudbury",
    "neighborhood": null,
    "offer": "rent",
    "units": [
      {
        "id": "11564798-1",
        "count": 12,
        "amiQualification": 30,
        "bedrooms": 1,
        "price": "",
        "priceRate": "monthly",
      },
      {
        "id": "11564798-2",
        "count": 44,
        "amiQualification": 60,
        "bedrooms": 1,
        "price": 1165,
        "priceRate": "monthly",
      },
    ],
    "assignment": "lottery",
    "listingDate": "2020-05-08T17:18:44Z",
    "applicationDueDate": "2020-06-20",
    "type": "apt",
  },
  {
    "title": "Modera",
    "id": "11564795",
    "slug": "modera",
    "cardinalDirection": "west",
    "city": "Framingham",
    "neighborhood": null,
    "offer": "rent",
    "units": [
      {
        "id": "11564795-1",
        "count": 3,
        "amiQualification": 80,
        "bedrooms": 3,
        "price": 1889,
        "priceRate": "monthly",
      },
      {
        "id": "11564795-2",
        "count": 2,
        "amiQualification": 80,
        "bedrooms": 0,
        "price": 1404,
        "priceRate": "monthly",
      },
      {
        "id": "11564795-3",
        "count": 10,
        "amiQualification": 80,
        "bedrooms": 1,
        "price": 1577,
        "priceRate": "monthly",
      },
      {
        "id": "11564795-4",
        "count": 12,
        "amiQualification": 80,
        "bedrooms": 2,
        "price": 1736,
        "priceRate": "monthly",
      },
    ],
    "assignment": "lottery",
    "listingDate": "2020-05-08T17:18:44Z",
    "applicationDueDate": "2020-06-23",
    "type": "apt",
  },
  {
    "title": "The Meeting House",
    "id": "11564797",
    "slug": "meeting-house",
    "cardinalDirection": null,
    "city": "Boston",
    "neighborhood": "Dorchester",
    "offer": "rent",
    "units": [
      {
        "id": "11564797-1",
        "count": 1,
        "amiQualification": 100,
        "bedrooms": 3,
        "price": 2946,
        "priceRate": "monthly",
      },
      {
        "id": "11564797-2",
        "count": 4,
        "amiQualification": 100,
        "bedrooms": 0,
        "price": 1984,
        "priceRate": "monthly",
      },
      {
        "id": "11564797-3",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 3,
        "price": 2155,
        "priceRate": "monthly",
      },
      {
        "id": "11564797-4",
        "count": 4,
        "amiQualification": 100,
        "bedrooms": 1,
        "price": 2125,
        "priceRate": "monthly",
      },
      {
        "id": "11564797-5",
        "count": 2,
        "amiQualification": 100,
        "bedrooms": 2,
        "price": 2550,
        "priceRate": "monthly",
      },
      {
        "id": "11564797-6",
        "count": 3,
        "amiQualification": 80,
        "bedrooms": 0,
        "price": 1472,
        "priceRate": "monthly",
      },
      {
        "id": "11564797-7",
        "count": 4,
        "amiQualification": 80,
        "bedrooms": 1,
        "price": 1569,
        "priceRate": "monthly",
      },
      {
        "id": "11564797-8",
        "count": 1,
        "amiQualification": 80,
        "bedrooms": 2,
        "price": 1874,
        "priceRate": "monthly",
      },
    ],
    "assignment": "lottery",
    "listingDate": "2020-05-08T17:18:44Z",
    "applicationDueDate": "2020-05-29",
    "type": "apt",
  },
  {
    "title": "275 Roxbury Street",
    "id": "11564799",
    "slug": "275-roxbury-street",
    "cardinalDirection": null,
    "city": "Boston",
    "neighborhood": "Roxbury",
    "offer": "rent",
    "units": [
      {
        "id": "11564799-1",
        "count": 1,
        "amiQualification": 30,
        "bedrooms": 1,
        "price": 1269,
        "priceRate": "monthly",
      },
    ],
    "assignment": "first",
    "listingDate": "2020-05-08T17:18:44Z",
    "applicationDueDate": "",
    "type": "apt",
  },
];
